version: '3.8'

services:
  # Servicio de la aplicación Node.js
  app:
    build: .
    ports:
      # Mantén esto para tu desarrollo local, pero en Railway no es necesario.
      # Railway te asignará un puerto dinámico.
      - "1640:3000"
    environment:
      NODE_ENV: production
      # Railway inyectará estas variables automáticamente desde la configuración de tu proyecto.
      # No necesitas un valor fijo aquí, Railway se encargará de esto.
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: mysql
      JWT_SECRET: ${JWT_SECRET}
      UPLOAD_DIR: ${UPLOAD_DIR}
    # --- DEBES ELIMINAR ESTO EN RAILWAY ---
    # Elimina esta dependencia. La base de datos de Railway no es un servicio local.
    # depends_on:
    #   - mariadb
    # ------------------------------------
    volumes:
      # Mantén este volumen si planeas almacenar archivos de forma persistente.
      # Railway ofrece volúmenes persistentes, pero la ruta podría variar.
      # Es recomendable manejar la persistencia de archivos de otra manera en la nube.
      - ./public/uploads:/src/src/app/public/uploads

  # --- DEBES ELIMINAR ESTO EN RAILWAY ---
  # Elimina todo este servicio. Railway ya provee un servicio de base de datos MySQL.
  # No necesitas levantar tu propia base de datos dentro del mismo proyecto.
  # mariadb:
  #   image: mariadb:10.6
  #   environment:
  #     MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #     MARIADB_DATABASE: ${DB_NAME}
  #     MARIADB_USER: ${DB_USER}
  #     MARIADB_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   ports:
  #     - "3307:3306"
  # ------------------------------------

# --- DEBES ELIMINAR ESTO EN RAILWAY ---
# Este volumen es solo para tu entorno local.
# volumes:
#   db_data:
# ------------------------------------
